PROJECT_DIR := $(CURDIR)
MKDOCS_CFG := $(CURDIR)/mkdocs.yml
DOCS_PYTHON := $(ROOT_CHECK_PYTHON)
DOCS_CACHE_DIR := $(ROOT_DOCS_CACHE_DIR)
DOCS_BUILD_SITE_DIR := $(ROOT_DOCS_BUILD_SITE_DIR)
DOCS_CHECK_SITE_DIR := $(ROOT_DOCS_CHECK_SITE_DIR)
DOCS_SERVE_SITE_DIR := $(ROOT_DOCS_SERVE_SITE_DIR)
DOCS_BUILD_CONFIG_FILE := $(CURDIR)/mkdocs.yml
DOCS_CHECK_CONFIG_FILE := $(CURDIR)/mkdocs.yml
DOCS_SERVE_CONFIG_FILE := $(ROOT_DOCS_SERVE_CFG)
DOCS_BASE_CONFIG_FILE := $(CURDIR)/mkdocs.yml
DOCS_SHARED_CONFIG_FILE ?= $(CURDIR)/mkdocs.shared.yml
DOCS_RENDERED_DOCS_DIR ?= $(CURDIR)/docs
DOCS_RENDER_SERVE_CONFIG ?= 1
DOCS_BUILD_BOOTSTRAP_TARGETS ?= root-check-env
DOCS_CHECK_BOOTSTRAP_TARGETS ?= root-check-env
DOCS_SERVE_BOOTSTRAP_TARGETS ?= root-check-env
DOCS_BUILD_PREPARE_TARGETS ?=
DOCS_CHECK_PREPARE_TARGETS ?=
DOCS_SERVE_PREPARE_TARGETS ?= docs-render-serve-config
DOCS_SERVE_GUARD_TARGETS ?= docs-assert-serve-port
DOCS_BUILD_PRE_CLEAN_PATHS ?= "$(ROOT_DOCS_BUILD_SITE_DIR)" "$(ROOT_DOCS_CACHE_DIR)"
DOCS_CHECK_PRE_CLEAN_PATHS ?= "$(ROOT_DOCS_CHECK_SITE_DIR)" "$(ROOT_DOCS_CACHE_DIR)"
DOCS_SERVE_PRE_CLEAN_PATHS ?= "$(ROOT_DOCS_SERVE_SITE_DIR)" "$(ROOT_DOCS_CACHE_DIR)"
DOCS_BUILD_ENV ?= DISABLE_MKDOCS_2_WARNING=true NO_MKDOCS_2_WARNING=true
DOCS_CHECK_ENV ?= DISABLE_MKDOCS_2_WARNING=true NO_MKDOCS_2_WARNING=true
DOCS_SERVE_ENV ?= DISABLE_MKDOCS_2_WARNING=true NO_MKDOCS_2_WARNING=true
DOCS_SERVE_FLAGS ?= --strict
DOCS_BUILD_SITE_URL ?= http://$(ROOT_DOCS_DEV_ADDR)/
DOCS_CHECK_SITE_URL ?= http://$(ROOT_DOCS_DEV_ADDR)/
DOCS_SERVE_SITE_URL ?= http://$(ROOT_DOCS_DEV_ADDR)/
DOCS_EXTRA_CLEAN_PATHS ?= "$(ROOT_DOCS_SERVE_CFG)" "$(ROOT_DOCS_CACHE_DIR)"

include $(ROOT_MAKE_DIR)/bijux-py/ci/docs.mk
