.DELETE_ON_ERROR:
.DEFAULT_GOAL ?= all
.SHELLFLAGS := -eu -o pipefail -c
SHELL := bash

PYTHON ?= python3.11
UV ?= uv
RM ?= rm -rf

PROJECT_DIR ?= $(CURDIR)
PROJECT_SLUG ?= $(notdir $(abspath $(PROJECT_DIR)))
PROJECT_ARTIFACTS_DIR ?= artifacts
ROOT_ARTIFACTS_DIR ?= $(PROJECT_ARTIFACTS_DIR)/root
ROOT_VENV ?= $(ROOT_ARTIFACTS_DIR)/venv
ROOT_PYCACHE_DIR ?= $(ROOT_ARTIFACTS_DIR)/pycache
ROOT_XDG_CACHE_DIR ?= $(ROOT_ARTIFACTS_DIR)/xdg_cache
ROOT_HYPOTHESIS_DIR ?= $(ROOT_ARTIFACTS_DIR)/hypothesis
ROOT_UV_CACHE_DIR ?= $(ROOT_ARTIFACTS_DIR)/uv_cache
ROOT_NPM_CACHE_DIR ?= $(ROOT_ARTIFACTS_DIR)/npm_cache
MKDOCS_CFG ?= $(PROJECT_DIR)/mkdocs.yml
SELF_MAKE ?= $(MAKE)
ROOT_NOTPARALLEL_TARGETS ?= all clean

.NOTPARALLEL: $(ROOT_NOTPARALLEL_TARGETS)

export PYTHONDONTWRITEBYTECODE ?= 1
export PYTHONPYCACHEPREFIX ?= $(ROOT_PYCACHE_DIR)
export XDG_CACHE_HOME ?= $(ROOT_XDG_CACHE_DIR)
export HYPOTHESIS_STORAGE_DIRECTORY ?= $(ROOT_HYPOTHESIS_DIR)
export UV_CACHE_DIR ?= $(ROOT_UV_CACHE_DIR)
export NPM_CONFIG_CACHE ?= $(ROOT_NPM_CACHE_DIR)
