#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
SCRIPT_REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = SCRIPT_REPO_ROOT / ".github/standards/repo-config.manifest.json"
PROVENANCE_HEADER = (
    "# SSOT NOTICE: This file is generated by bijux-std standards sync.\n"
    "# Source of truth: bijux-std/.github/standards/repo-config.manifest.json and "
    "bijux-std/shared/bijux-gh/workflows/.\n"
    "# Do not edit this generated copy directly.\n\n"
)


def resolve_repo_root(repo_name: str) -> Path:
    if SCRIPT_REPO_ROOT.name == repo_name:
        return SCRIPT_REPO_ROOT

    candidate = ROOT / repo_name
    if candidate.exists():
        return candidate

    raise FileNotFoundError(f"Unable to resolve repository root for '{repo_name}'")


def yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if value is None:
        return "null"

    text = str(value)
    if re.fullmatch(r"[A-Za-z0-9_./:@-]+", text):
        return text
    escaped = text.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def dump_yaml(obj: Any, indent: int = 0) -> list[str]:
    pad = " " * indent
    lines: list[str] = []

    if isinstance(obj, dict):
        for key, value in obj.items():
            if value is None:
                lines.append(f"{pad}{key}:")
                continue
            if isinstance(value, (dict, list)):
                lines.append(f"{pad}{key}:")
                lines.extend(dump_yaml(value, indent + 2))
            else:
                lines.append(f"{pad}{key}: {yaml_scalar(value)}")
        return lines

    if isinstance(obj, list):
        for item in obj:
            if isinstance(item, dict):
                lines.append(f"{pad}-")
                dict_lines = dump_yaml(item, indent + 2)
                if dict_lines:
                    first = dict_lines[0]
                    lines[-1] = f"{pad}- {first.strip()}"
                    lines.extend(dict_lines[1:])
            elif isinstance(item, list):
                lines.append(f"{pad}-")
                lines.extend(dump_yaml(item, indent + 2))
            else:
                lines.append(f"{pad}- {yaml_scalar(item)}")
        return lines

    lines.append(f"{pad}{yaml_scalar(obj)}")
    return lines


def render_release_env(entries: list[dict]) -> str:
    lines = ["# Unified release workflow configuration.", ""]
    for entry in entries:
        key = entry["key"]
        kind = entry["type"]
        value = entry["value"]

        if kind == "bool":
            rendered = "true" if value else "false"
        elif kind == "json":
            rendered = "'" + json.dumps(value, separators=(",", ":")) + "'"
        elif kind == "string":
            rendered = str(value)
        else:
            raise ValueError(f"Unsupported release.env entry type: {kind}")

        lines.append(f"{key}={rendered}")

    lines.append("")
    return PROVENANCE_HEADER + "\n".join(lines)


def render_yaml_document(data: Any) -> str:
    return PROVENANCE_HEADER + "\n".join(dump_yaml(data)) + "\n"


def normalize_labeler_rules(data: Any) -> Any:
    if not isinstance(data, dict):
        return data
    # actions/labeler supports these top-level config keys as scalars.
    option_keys = {"changed-files-labels-limit", "max-files-changed"}
    normalized: dict[str, Any] = {}
    for label, rules in data.items():
        if label in option_keys:
            normalized[label] = rules
            continue
        normalized[label] = rules if isinstance(rules, list) else [rules]
    return normalized


def validate_labeler_rules(data: Any) -> None:
    if not isinstance(data, dict):
        raise ValueError("labeler config must be a mapping")
    option_keys = {"changed-files-labels-limit", "max-files-changed"}
    for key, value in data.items():
        if key in option_keys:
            continue
        if not isinstance(value, list):
            raise ValueError(
                f"labeler config entry '{key}' must be a list of rule objects"
            )
        for index, item in enumerate(value):
            if not isinstance(item, dict):
                raise ValueError(
                    f"labeler config entry '{key}' item #{index + 1} must be a mapping"
                )


def find_repo_config(manifest: dict, repo_name: str) -> dict:
    for repo in manifest["repositories"]:
        if repo["name"] == repo_name:
            return repo
    raise KeyError(f"Repository '{repo_name}' not found in manifest")


def write_if_needed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def remove_if_generated(path: Path) -> None:
    if not path.exists():
        return
    content = path.read_text(encoding="utf-8")
    if content.startswith(PROVENANCE_HEADER):
        path.unlink()


def render_repo(repo_name: str, manifest: dict) -> None:
    repo = find_repo_config(manifest, repo_name)
    repo_root = resolve_repo_root(repo_name)

    release_path = repo_root / ".github/release.env"
    release_content = render_release_env(repo.get("release_env", []))
    write_if_needed(release_path, release_content)

    dependabot_data = repo.get("dependabot")
    if dependabot_data is not None:
        dependabot_path = repo_root / ".github/dependabot.yml"
        dependabot_content = render_yaml_document(dependabot_data)
        write_if_needed(dependabot_path, dependabot_content)

    labeler_data = repo.get("labeler")
    if labeler_data is not None:
        labeler_path = repo_root / ".github/labeler.yml"
        normalized_labeler = normalize_labeler_rules(labeler_data)
        validate_labeler_rules(normalized_labeler)
        labeler_content = render_yaml_document(normalized_labeler)
        write_if_needed(labeler_path, labeler_content)

    codecov_data = repo.get("codecov")
    if codecov_data is not None:
        codecov_path = repo_root / ".github/codecov.yml"
        codecov_content = render_yaml_document(codecov_data)
        write_if_needed(codecov_path, codecov_content)

    wrappers = repo.get("workflow_wrappers", {})
    wrapper_paths = {
        "ci": repo_root / ".github/workflows/ci.yml",
        "verify": repo_root / ".github/workflows/verify.yml",
    }
    for wrapper_name, wrapper_path in wrapper_paths.items():
        wrapper_definition = wrappers.get(wrapper_name)
        if wrapper_definition is None:
            remove_if_generated(wrapper_path)
            continue
        write_if_needed(wrapper_path, render_yaml_document(wrapper_definition))


def main() -> None:
    parser = argparse.ArgumentParser(description="Render release.env, dependabot.yml, labeler.yml, codecov.yml, and workflow wrappers from manifest")
    parser.add_argument("--manifest", default=str(MANIFEST_PATH), help="Path to manifest JSON")
    parser.add_argument("--repo", action="append", default=[], help="Repository name (repeatable)")
    args = parser.parse_args()

    manifest = json.loads(Path(args.manifest).read_text(encoding="utf-8"))
    repos = args.repo or [repo["name"] for repo in manifest["repositories"]]

    for repo_name in repos:
        render_repo(repo_name, manifest)


if __name__ == "__main__":
    main()
