.DELETE_ON_ERROR:
.DEFAULT_GOAL := help

SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c

PROJECT_ROOT ?= $(CURDIR)
PROJECT_ROOT := $(abspath $(PROJECT_ROOT))
ARTIFACT_ROOT ?= artifacts
ARTIFACT_ROOT_ABS := $(abspath $(ARTIFACT_ROOT))
BIJUX_ARTIFACT_BOUNDARY := $(abspath $(PROJECT_ROOT)/artifacts)
RUN_ID ?= local
BIJUX_MAKE ?= $(MAKE) --no-print-directory

BIJUX_FORMAT_TARGETS ?=
BIJUX_FMT_TARGETS ?=
BIJUX_LINT_TARGETS ?=
BIJUX_TEST_TARGETS ?=
BIJUX_TEST_SLOW_TARGETS ?=
BIJUX_TEST_ALL_TARGETS ?=
BIJUX_AUDIT_TARGETS ?=
BIJUX_SECURITY_TARGETS ?=
BIJUX_COVERAGE_TARGETS ?=
BIJUX_DOCTOR_TARGETS ?=
BIJUX_CI_FAST_TARGETS ?=
BIJUX_CI_PR_TARGETS ?=
BIJUX_CI_NIGHTLY_TARGETS ?=
BIJUX_CI_DOCS_TARGETS ?=
BIJUX_HELP_TARGETS ?=
